spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo1
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    az.coftea.*: debug